name: default-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'test'
        default: 'World'
        required: true
        type: string

env:
  BUILD_TYPE: Debug
  
jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: job-configure
      run: sudo ./configure 0.0.1 OFF 2
      env:
        MY_VAR_1: "one"
        MY_VAR_2: "two"
        MY_VAR_3: "three"

    - name: job-build
      run: make build

    - name: job-upload-artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: ${{github.workspace}}/Nucleo-h743zi2/build/nuc-h7-uvc.bin
